<?php
if(isset($_SESSION['make']))
{
unset($_SESSION['make']);       
}
if(isset($_SESSION['model']))
{
unset($_SESSION['model']);       
}
if(isset($_SESSION['colour']))
{
unset($_SESSION['colour']);       
}
if(isset($_SESSION['min_price']))
{
unset($_SESSION['min_price']);       
}
if(isset($_SESSION['max_price']))
{
unset($_SESSION['max_price']);       
}
if(isset($_SESSION['town']))
{
unset($_SESSION['town']);       
}
if(isset($_SESSION['region']))
{
unset($_SESSION['region']);       
}
if(isset($_SESSION['reg']))
{
unset($_SESSION['reg']);       
}     

?>